--Q1 Total Number of Campaigns
SELECT COUNT(*) AS TOTAL_CAMPAIGNS
FROM GOOGLE_ADS_PERFORMANCE;

--Q2 TYPES OF KEYWORDS CLICKED AND THEIR AVERAGE
SELECT KEYWORD_CATEGORY,AVG(CLICKS) AS KEYWORDS_CLICKED
FROM GOOGLE_ADS_PERFORMANCE
GROUP BY KEYWORD_CATEGORY
ORDER BY KEYWORDS_CLICKED DESC;

--Q3 ROI ON DEVICES
SELECT DEVICE, SUM(SALE_AMOUNT) - SUM(COST) AS ROI
FROM GOOGLE_ADS_PERFORMANCE
GROUP BY DEVICE
ORDER BY ROI DESC;

--Q4 Best-performing keyword category by ROI
SELECT KEYWORD_CATEGORY, SUM(SALE_AMOUNT) - SUM(COST) AS ROI
FROM GOOGLE_ADS_PERFORMANCE
GROUP BY KEYWORD_CATEGORY
ORDER BY ROI DESC;

--Q5 Ads with high spend but low conversion
SELECT ad_id,cost,conversions
FROM google_ads_performance
WHERE cost > (
    SELECT AVG(cost) FROM google_ads_performance
)
AND conversions < (
    SELECT AVG(conversions) FROM google_ads_performance
);

--Q6 AVG CLICKS ON DEVICES
SELECT DEVICE,AVG(CLICKS) AS AVG_CLICK_DEVICES
FROM GOOGLE_ADS_PERFORMANCE
GROUP BY DEVICE
ORDER BY AVG_CLICK_DEVICES;

--Q7 AVG LEADS ON DEVICES
SELECT DEVICE,AVG(LEADS) AS AVG_LEADS_DEVICES
FROM GOOGLE_ADS_PERFORMANCE
GROUP BY DEVICE
ORDER BY AVG_LEADS_DEVICES;

--Q8 AVG CONVERSIONS ON DEVICES
SELECT DEVICE,AVG(CONVERSIONS) AS AVG_CONVERSIONS_DEVICES
FROM GOOGLE_ADS_PERFORMANCE
GROUP BY DEVICE
ORDER BY AVG_CONVERSIONS_DEVICES;

--Q9 KEYWORDS AND LEADS WHICH WE GET
SELECT KEYWORD_CATEGORY,AVG(LEADS),AVG(CONVERSIONS)
FROM GOOGLE_ADS_PERFORMANCE
GROUP BY KEYWORD_CATEGORY;

--Q10 TOTAL CPC ON DEVICES
SELECT KEYWORD_CATEGORY,SUM(CPC) AS CPC_KEYWORD
FROM GOOGLE_ADS_PERFORMANCE
GROUP BY KEYWORD_CATEGORY;

--Q11 TOTAL COST,CLICKS,SALES
SELECT CAMPAIGN_NAME,SUM(COST),SUM(CLICKS),SUM(SALE_AMOUNT)
FROM GOOGLE_ADS_PERFORMANCE
GROUP BY CAMPAIGN_NAME;

--Q12 SALES ON DEVICES
SELECT DEVICE,AVG(SALE_AMOUNT)AS AVG_SALES
FROM GOOGLE_ADS_PERFORMANCE
GROUP BY DEVICE;

--Q13 TOTAL COST OF CAMPAIGNS
SELECT SUM(COST) AS TOTAL_COST
FROM GOOGLE_ADS_PERFORMANCE;

--Q14 TOTAL SALES AMOUNT
SELECT SUM(SALE_AMOUNT) AS TOTAL_SALES
FROM GOOGLE_ADS_PERFORMANCE;

--Q15 AVG IMPRESSIONS AND AVG CLICKS)
SELECT AVG(CLICKS),AVG(IMPRESSIONS) 
FROM GOOGLE_ADS_PERFORMANCE;

--Q16 Device with best cost efficiency (lowest CPC)
SELECT DEVICE,SUM(CPC) AS AVG_CPC
FROM GOOGLE_ADS_PERFORMANCE
GROUP BY DEVICE
ORDER BY AVG_CPC;

--Q17 Daily sales trend
SELECT ad_date, SUM(sale_amount) AS daily_sales
FROM google_ads_performance
GROUP BY ad_date
ORDER BY ad_date;

--Q18 Daily Conversions Trends IN DESCENDING
SELECT AD_DATE,SUM(CONVERSIONS) AS DAY_CONVERSIONS
FROM GOOGLE_ADS_PERFORMANCE
GROUP BY AD_DATE
ORDER BY DAY_CONVERSIONS DESC;

--Q19 ADS Peforming better than expected
SELECT AD_ID,CAMPAIGN_NAME,CONVERSION_RATE
FROM GOOGLE_ADS_PERFORMANCE
WHERE CONVERSION_RATE > (SELECT AVG(CONVERSION_RATE) FROM GOOGLE_ADS_PERFORMANCE);

--Q20 Rank devices by total sales
SELECT device,SUM(sale_amount) AS total_sales,
RANK() OVER (ORDER BY SUM(sale_amount) DESC) AS sales_rank
FROM google_ads_performance
GROUP BY device;


