--Q1 Total Number of Campaigns
SELECT COUNT(*) AS TOTAL_CAMPAIGNS
FROM GOOGLE_ADS_PERFORMANCE;

--Q2 TYPES OF KEYWORDS CLICKED AND THEIR AVERAGE
SELECT KEYWORD_CATEGORY,AVG(CLICKS) AS KEYWORDS_CLICKED
FROM GOOGLE_ADS_PERFORMANCE
GROUP BY KEYWORD_CATEGORY
ORDER BY KEYWORDS_CLICKED DESC;

--Q3 TOTAL COST OF CAMPAIGNS
SELECT SUM(COST) AS TOTAL_COST
FROM GOOGLE_ADS_PERFORMANCE;

--Q4 TOTAL SALES AMOUNT
SELECT SUM(SALE_AMOUNT) AS TOTAL_SALES
FROM GOOGLE_ADS_PERFORMANCE;

--Q5 AVG IMPRESSIONS AND AVG CLICKS)
SELECT AVG(CLICKS),AVG(IMPRESSIONS) 
FROM GOOGLE_ADS_PERFORMANCE;

--Q6 AVG CLICKS ON DEVICES
SELECT DEVICE,AVG(CLICKS) AS AVG_CLICK_DEVICES
FROM GOOGLE_ADS_PERFORMANCE
GROUP BY DEVICE
ORDER BY AVG_CLICK_DEVICES;

--Q7 AVG LEADS ON DEVICES
SELECT DEVICE,AVG(LEADS) AS AVG_LEADS_DEVICES
FROM GOOGLE_ADS_PERFORMANCE
GROUP BY DEVICE
ORDER BY AVG_LEADS_DEVICES;

--Q8 AVG CONVERSIONS ON DEVICES
SELECT DEVICE,AVG(CONVERSIONS) AS AVG_CONVERSIONS_DEVICES
FROM GOOGLE_ADS_PERFORMANCE
GROUP BY DEVICE
ORDER BY AVG_CONVERSIONS_DEVICES;

--Q9 KEYWORDS AND LEADS WHICH WE GET
SELECT KEYWORD_CATEGORY,AVG(LEADS),AVG(CONVERSIONS)
FROM GOOGLE_ADS_PERFORMANCE
GROUP BY KEYWORD_CATEGORY;

--Q10 TOTAL CPC ON DEVICES
SELECT KEYWORD_CATEGORY,SUM(CPC) AS CPC_KEYWORD
FROM GOOGLE_ADS_PERFORMANCE
GROUP BY KEYWORD_CATEGORY;

--Q11 TOTAL COST,CLICKS,SALES
SELECT CAMPAIGN_NAME,SUM(COST),SUM(CLICKS),SUM(SALE_AMOUNT)
FROM GOOGLE_ADS_PERFORMANCE
GROUP BY CAMPAIGN_NAME;

--Q12 SALES ON DEVICES
SELECT DEVICE,AVG(SALE_AMOUNT)AS AVG_SALES
FROM GOOGLE_ADS_PERFORMANCE
GROUP BY DEVICE;
